jwan_dbt:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: localhost  # This should match the Docker host, usually localhost for local development
      port: 5438       # Ensure this matches the Docker port mapping
      user: postgres
      password: jwan_dbt
      dbname: bookings
      schema: analytics
  target: dev
